/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Staff = React.memo(function Staff(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/staff-transformed.glb");
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.0075;
  });

  return (
    <group
      {...props}
      dispose={null}
           scale={[3, 3, 3]}
      position={[0, -2, 0.1, 0.06]}
      ref={modelRef}
    >

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wizard_Staff3_Wizard_Staff3_0_3.geometry}
        material={materials.Wizard_Staff3}
        position={[-0.061, 0.783, 0.168]}
        rotation={[0.0001, Math.PI / -4.9, 0.02]}
        scale={1.59}
      />

    </group>
  );
});

export default Staff;
useGLTF.preload("/models/staff-transformed.glb");
